<a href="https://colab.research.google.com/github/artgora43/Tareas-THC/blob/main/Trabajo_de_clase_29_10_2024_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a=np.array([1,2,3]) #Esto es un arreglo
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3]


In [ ]:
dim_cero=np.array(1) #arreglo de dimensión cero
print(dim_cero) #escalar

1


In [ ]:
dim_uno=np.array([2,1]) #arreglo de dimensión uno
print(dim_uno) #vector

[2 1]


In [ ]:
dim_dos=np.array([[1,2],[3,4]]) #arreglo de dimensión dos, los arreglos se caracterizan por el número de corchetes que contienen
print(dim_dos) #matriz

[[1 2]
 [3 4]]


In [ ]:
print(dim_uno.ndim) #imprime la dimensión
print(dim_uno.shape) #imprime la cantidad de elementos
print(dim_dos.shape) #imprime filas y columnas

1
(2,)
(2, 2)


In [ ]:
import numpy as np
A=np.array([[1,'o'],[0,0]]) #solo puede haber un tipo de dato en los arreglos
print(A)

[['1' 'o']
 ['0' '0']]


In [ ]:
vec=np.array([2,0,-1,4,5])
print(vec[0]) #para acceder a los elementos del arreglo es similar con las listas
print(vec[3])

2
4


In [ ]:
print(vec[1:3]) #para el slicing se debe anotar un número anterior al primero y posterior al último
print(vec[1:4])
print(vec[2:5])
n=len(vec)
print(n)

[ 0 -1]
[ 0 -1  4]
[-1  4  5]
5


In [ ]:
vec=np.array([2,0,-1,4,5,6,7,8,9,10])
print(vec[1:10:2]) #en orden, donde empiezo, hasta donde llego, de cuanto en cuanto
print(vec[1:10:5])

[ 0  4  6  8 10]
[0 7]


In [ ]:
Mat=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) #Las listas están indexadas, en orden, 0,1,2
print(Mat[0,0]) #En orden, el índice de la lista, índice del elemento
print(Mat[2,2])
print(Mat[1,-1]) #el último elemento en la lista se puede tomar con -1
print(Mat[-1,-1]) #tambíen el índice de la lista
#print(Math[1,4]): error de sintáxis

1
11
8
12


In [ ]:
print(Mat[:,1]) #imprime el elemento uno de cada lista, selecciona la columna 1 (de la matriz creada por el arreglo)
print(Mat[1,:]) #selecciona la fila 1 de la matriz
print(Mat[1,1:4]) #Doble barrido
print(Mat[1:3,2]) #imprime elementos de la columna
print(Mat[1:3,1:4]) #en orden, controla filas, controla columnas
print(Mat[0:2,0:3])

[ 2  6 10]
[5 6 7 8]
[6 7 8]
[ 7 11]
[[ 6  7  8]
 [10 11 12]]
[[1 2 3]
 [5 6 7]]


In [53]:
a=np.array([1,2,3,4])
b=np.array([4,5,6,7])
print(a+b)
n=len(a)
for i in range(n):
  producto=a[i]*b[i]+producto
  print(producto)


[ 5  7  9 11]
452
462
480
508


In [ ]:
Mat=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(Mat+Mat)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


[ 4 10 18 28]
